# Docker compose CloudGen Access Proxy
---
version: '3.5'
services:

  envoy:
    container_name: envoy
    depends_on:
      - orchestrator
    environment:
      - FYDE_PROXY_HOST=orchestrator
      - FYDE_PROXY_PORT=50051
    image: fydeinc/envoyproxy-centos:latest
    networks:
      - cga
    ports:
      # Publicly exposed CloudGen Access Proxy port
      # Host port must match the one defined in CloudGen Enterprise Console
      - "443:8000"
    restart: unless-stopped

  orchestrator:
    container_name: orchestrator
    environment:
      # Update with CloudGen Access Proxy enrollment link
      - FYDE_ENROLLMENT_TOKEN=https://enterprise.fyde.com/proxies/v2/enrollment/3661d12d-e973-4b08-b6a3-35b0fb90fef7?proxy_auth_token=hogZ4JQA3JpoJLz6tWVsQoLS&tenant_id=cd657b26-d0ca-4b6e-b212-f87191b0bf79
    image: fydeinc/fydeproxy:latest
    networks:
      - cga
    restart: unless-stopped

networks:
  cga:
    name: cga
